- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: latest

- name: download code
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Remove all files
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: copy the html docs
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html
    remote_src: yes

- name: copy roboshop config file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start nginx service
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
